sudo: required
language: java
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_a6a69c5b1756_key -iv $encrypted_a6a69c5b1756_iv
  -in secrets/client-secret.json.enc -out client-secret.json -d
- openssl aes-256-cbc -K $encrypted_a6a69c5b1756_key -iv $encrypted_a6a69c5b1756_iv
  -in secrets/cloud-sql-secret.json.enc -out cloud-sql-secret.json -d
install:
- mvn -P prod install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn -P prod test -B
deploy:
  provider: gae
  project: moltimate
  keyfile: client-secret.json
  on: master
