# Used by GCP App Engine
runtime: java8
inbound_services:
  - warmup
derived_file_type:
  - java_precompiled
threadsafe: True
auto_id_policy: default
api_version: 'none'
handlers:
  - url: /.*
    script: unused
    login: optional
    secure: optional
skip_files:
  - .git/
  - .github/
  - target/
  - moltimate.mv.db
