spring:
  datasource:
    url: jdbc:h2:./moltimate;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE
    username: root
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.biojava: OFF
